export const workers = [
  {
    id: 1,
    name: 'Rajesh Kumar',
    role: 'Mason & RCC Professional',
    emoji: '👷',
    header: 'orange',
    avatarBg: 'orange',
    rating: 4.8,
    reviews: 124,
    exp: 10,
    location: 'Sagar, MP',
    verified: true,
    topRated: true,
    skills: ['Brickwork', 'RCC', 'Plaster', 'Tile Work'],
    category: 'railway',
    about: 'Railway siding and RCC specialist with 10+ years on bridge and platform projects.',
    projectsCompleted: 42,
    available: true,
  },
  {
    id: 2,
    name: 'Priya Sharma',
    role: 'Water Project Engineer',
    emoji: '💧',
    header: 'teal',
    avatarBg: 'teal',
    rating: 4.9,
    reviews: 89,
    exp: 8,
    location: 'Bhopal, MP',
    verified: true,
    topRated: true,
    skills: ['Pipeline', 'WTP', 'Pumping Stations', 'Distribution Network'],
    category: 'water',
    about: 'Water supply engineer for Jal Jeevan Mission pipeline and WTP projects.',
    projectsCompleted: 24,
    available: true,
  },
  {
    id: 3,
    name: 'Vikram Singh',
    role: 'Railway Track Electrician',
    emoji: '⚡',
    header: 'gold',
    avatarBg: 'gold',
    rating: 4.7,
    reviews: 203,
    exp: 15,
    location: 'Delhi',
    verified: true,
    topRated: false,
    skills: ['Signalling', 'Overhead Wiring', 'Panel Board'],
    category: 'railway',
    about: 'Signalling and OHE specialist for railway electrification projects.',
    projectsCompleted: 58,
    available: true,
  },
  {
    id: 4,
    name: 'Amit Patel',
    role: 'Civil Engineer (Bridges)',
    emoji: '📐',
    header: 'orange',
    avatarBg: 'blue',
    rating: 4.6,
    reviews: 67,
    exp: 12,
    location: 'Mumbai',
    verified: true,
    topRated: false,
    skills: ['Structural Design', 'Estimation', 'BOQ'],
    category: 'railway',
    about: 'Structural engineer for railway bridges, ROBs and approach roads.',
    projectsCompleted: 31,
    available: true,
  },
  {
    id: 5,
    name: 'Ramesh Verma',
    role: 'Water Tank & Structure Builder',
    emoji: '🏗️',
    header: 'teal',
    avatarBg: 'gold',
    rating: 4.9,
    reviews: 156,
    exp: 20,
    location: 'Jaipur',
    verified: true,
    topRated: true,
    skills: ['ESR Towers', 'Underground Sumps', 'RCC Tanks'],
    category: 'water',
    about: 'Elevated storage reservoir (ESR) and sump construction expert.',
    projectsCompleted: 55,
    available: true,
  },
  {
    id: 6,
    name: 'Suresh Yadav',
    role: 'Road Line & Drainage Worker',
    emoji: '🛣️',
    header: 'gold',
    avatarBg: 'orange',
    rating: 4.5,
    reviews: 98,
    exp: 12,
    location: 'Lucknow',
    verified: false,
    topRated: false,
    skills: ['Road Marking', 'Drainage', 'Road Furniture'],
    category: 'road',
    about: 'Highway finishing specialist — markings, drainage and road furniture.',
    projectsCompleted: 41,
    available: true,
  },
  {
    id: 7,
    name: 'Mahesh Gupta',
    role: 'Road Contractor & Site Supervisor',
    emoji: '🏗️',
    header: 'orange',
    avatarBg: 'teal',
    rating: 4.8,
    reviews: 312,
    exp: 18,
    location: 'Pune',
    verified: true,
    topRated: true,
    skills: ['Highway Construction', 'Asphalt', 'Labour Management'],
    category: 'road',
    about: 'Highway and road contractor with 18 years across NH and state highways.',
    projectsCompleted: 76,
    available: true,
  },
  {
    id: 8,
    name: 'Neha Joshi',
    role: 'Highway Surveyor & AutoCAD',
    emoji: '🖥️',
    header: 'teal',
    avatarBg: 'gold',
    rating: 4.7,
    reviews: 74,
    exp: 6,
    location: 'Hyderabad',
    verified: true,
    topRated: false,
    skills: ['Surveying', 'AutoCAD', 'Leveling'],
    category: 'road',
    about: 'Surveyor for road alignment and earthwork measurement.',
    projectsCompleted: 29,
    available: true,
  },
  {
    id: 9,
    name: 'Arun Thakur',
    role: 'Welder & Fabricator',
    emoji: '🔩',
    header: 'gold',
    avatarBg: 'orange',
    rating: 4.6,
    reviews: 87,
    exp: 14,
    location: 'Bangalore',
    verified: true,
    topRated: false,
    skills: ['Arc Welding', 'MIG Welding', 'MS Fabrication'],
    category: 'railway',
    about: 'Welding specialist for rail structures, bridges and culverts.',
    projectsCompleted: 63,
    available: true,
  },
  {
    id: 10,
    name: 'Sunil Verma',
    role: 'Residential Mason & Finisher',
    emoji: '🧱',
    header: 'teal',
    avatarBg: 'gold',
    rating: 4.7,
    reviews: 141,
    exp: 9,
    location: 'Gwalior, MP',
    verified: true,
    topRated: false,
    skills: ['Brickwork', 'Plaster', 'Flooring', 'Tile Work'],
    category: 'residential',
    about: 'Home construction specialist — from foundation to finishing.',
    projectsCompleted: 38,
    available: true,
  },
  {
    id: 11,
    name: 'Deepa Nair',
    role: 'Interior Designer',
    emoji: '🛋️',
    header: 'gold',
    avatarBg: 'teal',
    rating: 4.8,
    reviews: 96,
    exp: 11,
    location: 'Indore',
    verified: true,
    topRated: true,
    skills: ['Interior Design', 'Modular Kitchen', '3D Modeling'],
    category: 'residential',
    about: 'End-to-end home interior design and execution.',
    projectsCompleted: 67,
    available: true,
  },
  {
    id: 12,
    name: 'Mohan Lal',
    role: 'Electrician (Home)',
    emoji: '⚡',
    header: 'orange',
    avatarBg: 'orange',
    rating: 4.6,
    reviews: 178,
    exp: 16,
    location: 'Bhopal, MP',
    verified: true,
    topRated: false,
    skills: ['Wiring', 'Smart Home', 'Solar'],
    category: 'residential',
    about: 'Home electrical wiring, smart automation and solar installation.',
    projectsCompleted: 120,
    available: true,
  },
]

export const constructionStages = [
  'Planning & Estimation',
  'Foundation',
  'Plinth',
  'RCC Structure',
  'Brickwork',
  'Plaster',
  'Electrical & Plumbing',
  'Flooring',
  'Painting',
  'Doors & Windows',
  'Interior & Final Handover',
]

export const dashboardStats = [
  { icon: '📊', iconClass: 'orange', value: '46%', label: 'Project Progress' },
  { icon: '💰', iconClass: 'teal', value: '₹25L', label: 'Total Budget' },
  { icon: '📉', iconClass: 'gold', value: '₹11.2L', label: 'Actual Expense' },
  { icon: '👷', iconClass: 'blue', value: '18', label: 'Workers Today' },
]

export const materials = [
  { name: 'Cement', purchased: '400 bags', used: '280 bags', balance: '120 bags', status: 'Adequate', statusClass: 'teal' },
  { name: 'Steel', purchased: '8 MT', used: '6.5 MT', balance: '1.5 MT', status: 'Low', statusClass: 'gold' },
  { name: 'Bricks', purchased: '15,000', used: '9,000', balance: '6,000', status: 'Adequate', statusClass: 'teal' },
  { name: 'Sand', purchased: '40 m³', used: '32 m³', balance: '8 m³', status: 'Reorder', statusClass: 'orange' },
  { name: 'Aggregate', purchased: '30 m³', used: '22 m³', balance: '8 m³', status: 'Adequate', statusClass: 'teal' },
]

export const team = [
  { name: 'Rajesh Kumar', role: 'Mason', emoji: '👷', bg: 'var(--saffron), var(--gold)', status: 'Online', online: true },
  { name: 'Vikram Singh', role: 'Electrician', emoji: '⚡', bg: 'var(--teal), #4ECDC4', status: 'Offline', online: false },
  { name: 'Sunil Verma', role: 'Plumber', emoji: '🔧', bg: 'var(--gold), #FFD700', status: 'Online', online: true },
  { name: 'Amit Patel', role: 'Civil Engineer', emoji: '📐', bg: '#3B82F6, #60A5FA', status: 'Offline', online: false },
]

export const activities = [
  { icon: '🧱', text: <><strong>Rajesh Kumar</strong> completed brickwork on first floor east wall</>, time: '2 hours ago' },
  { icon: '📸', text: <><strong>Site photos</strong> uploaded - 12 new images</>, time: '4 hours ago' },
  { icon: '💰', text: <><strong>Payment</strong> of ₹1,20,000 processed for cement purchase</>, time: 'Yesterday' },
  { icon: '📦', text: <><strong>Material delivery</strong> - 5000 bricks received at site</>, time: '2 days ago' },
  { icon: '⚠️', text: <><strong>Sand stock</strong> running low - reorder recommended</>, time: '3 days ago' },
]

export const reviews = [
  {
    initials: 'SK',
    color: 'var(--teal)',
    author: 'Suresh Khanna',
    meta: 'Residential Project • 2 months ago',
    stars: 5,
    text: 'Excellent work on our house construction. Rajesh and his team were very professional and completed the masonry work ahead of schedule. Quality of brickwork and plastering was outstanding. Highly recommended!',
  },
  {
    initials: 'AM',
    color: 'var(--saffron)',
    author: 'Anita Mehta',
    meta: 'Renovation Project • 4 months ago',
    stars: 5,
    text: 'Hired Rajesh for bathroom renovation and tile work. Very skilled and honest pricing. The tile work was flawless. Will definitely hire again for future projects.',
  },
  {
    initials: 'RP',
    color: 'var(--gold)',
    author: 'Ramesh Patel',
    meta: 'Commercial Building • 6 months ago',
    stars: 4,
    text: 'Good RCC work for our commercial building. Rajesh understands structural requirements well. Minor delays due to weather but overall satisfied with the quality.',
  },
]

// ===== V3: COMPANIES & BUSINESS NETWORK =====
export const companies = [
  {
    id: 1,
    name: 'Rajesh Construction Services',
    type: 'Contractor',
    emoji: '🏗️',
    avatarBg: 'orange',
    header: 'orange',
    rating: 4.8,
    reviews: 87,
    exp: 12,
    location: 'Sagar, Madhya Pradesh',
    verified: true,
    topRated: true,
    teamSize: '25+ Workers',
    projectValue: '₹12 Cr',
    projects: 64,
    specialization: 'Residential & RCC Structures',
    tags: ['RCC', 'Brickwork', 'Full Turnkey', 'Labour Contractor'],
    description: 'Full-service civil contracting firm specialising in residential and commercial RCC structures with an in-house team of skilled masons, bar benders, shuttering and RCC workers.',
  },
  {
    id: 2,
    name: 'Sharma & Associates Architects',
    type: 'Architecture Firm',
    emoji: '📐',
    avatarBg: 'teal',
    header: 'teal',
    rating: 4.9,
    reviews: 42,
    exp: 15,
    location: 'Bhopal, Madhya Pradesh',
    verified: true,
    topRated: true,
    teamSize: '6 Architects',
    projectValue: '₹45 Cr',
    projects: 120,
    specialization: 'Architecture, Planning & Design',
    tags: ['Architecture', '3D Design', 'Vastu', 'Building Plans'],
    description: 'Award-winning architecture firm delivering residential, commercial and institutional design with in-house 3D visualisation, structural coordination and government approval support.',
  },
  {
    id: 3,
    name: 'Global Interior Concepts',
    type: 'Interior Firm',
    emoji: '🛋️',
    avatarBg: 'gold',
    header: 'gold',
    rating: 4.7,
    reviews: 58,
    exp: 9,
    location: 'Indore, Madhya Pradesh',
    verified: true,
    topRated: false,
    teamSize: '18 Designers',
    projectValue: '₹8 Cr',
    projects: 210,
    specialization: 'Residential & Office Interiors',
    tags: ['Modular Kitchen', 'False Ceiling', 'Wall Panelling', 'Furniture'],
    description: 'End-to-end interior design and execution for homes, offices and retail — from 3D concepts to modular furniture, lighting and final styling.',
  },
  {
    id: 4,
    name: 'National Steel & Materials Pvt Ltd',
    type: 'Material Supplier',
    emoji: '🏭',
    avatarBg: 'teal',
    header: 'teal',
    rating: 4.6,
    reviews: 134,
    exp: 20,
    location: 'Nagpur, Maharashtra',
    verified: true,
    topRated: true,
    teamSize: '40 Staff',
    projectValue: '₹80 Cr / yr',
    projects: 900,
    specialization: 'Steel, Cement & Construction Materials',
    tags: ['TMT Steel', 'Cement', 'Sand & Aggregate', 'Tiles'],
    description: 'Leading distributor of TMT steel, cement, aggregates and tiles with pan-Maharashtra delivery fleet and GST-invoiced transparent pricing for contractors and homeowners.',
  },
  {
    id: 5,
    name: 'Bhagirathi Equipment Rentals',
    type: 'Equipment Provider',
    emoji: '🚜',
    avatarBg: 'orange',
    header: 'orange',
    rating: 4.5,
    reviews: 71,
    exp: 8,
    location: 'Pune, Maharashtra',
    verified: true,
    topRated: false,
    teamSize: '30 Operators',
    projectValue: '₹5 Cr / yr',
    projects: 340,
    specialization: 'Construction Equipment Rental',
    tags: ['JCB', 'Crane', 'Concrete Mixer', 'Vibrator'],
    description: 'Rental fleet of JCBs, cranes, concrete mixers and compaction equipment with trained operators and same-day site deployment across Western India.',
  },
  {
    id: 6,
    name: 'Verma Structural Consultants',
    type: 'Consultancy',
    emoji: '📊',
    avatarBg: 'gold',
    header: 'gold',
    rating: 4.9,
    reviews: 37,
    exp: 18,
    location: 'Mumbai, Maharashtra',
    verified: true,
    topRated: true,
    teamSize: '9 Engineers',
    projectValue: '₹60 Cr',
    projects: 180,
    specialization: 'Structural & MEP Consultancy',
    tags: ['Structural Design', 'Soil Testing', 'MEP', 'Audits'],
    description: 'Structural design, vetting, soil investigation and MEP coordination for buildings and infrastructure — with IIT-credentialed principal engineers and bank-approved reports.',
  },
  {
    id: 7,
    name: 'Urbanrise Developers & Builders',
    type: 'Real Estate / Builder',
    emoji: '🏢',
    avatarBg: 'teal',
    header: 'teal',
    rating: 4.4,
    reviews: 96,
    exp: 15,
    location: 'Ahmedabad, Gujarat',
    verified: true,
    topRated: false,
    teamSize: '120 Staff',
    projectValue: '₹150 Cr',
    projects: 28,
    specialization: 'Group Housing & Commercial',
    tags: ['Group Housing', 'RERA Registered', 'Commercial', 'Turnkey'],
    description: 'RERA-registered developer delivering gated residential communities and commercial complexes with in-house construction, sales and after-sales teams.',
  },
  {
    id: 8,
    name: 'Sita Sub-Contracting Co.',
    type: 'Subcontractor',
    emoji: '🔩',
    avatarBg: 'orange',
    header: 'orange',
    rating: 4.7,
    reviews: 44,
    exp: 14,
    location: 'Jaipur, Rajasthan',
    verified: true,
    topRated: false,
    teamSize: '40 Workers',
    projectValue: '₹18 Cr',
    projects: 150,
    specialization: 'RCC, MEP & MEP Subcontracts',
    tags: ['RCC Subcontract', 'Electrical', 'Plumbing', 'Fire Fighting'],
    description: 'Specialised subcontracting firm providing labour-and-materials crews for RCC works, electrical, plumbing and fire-fighting packages on large projects.',
  },
]

// ===== V4: GOVERNMENT TENDERS =====
export const tenders = [
  {
    id: 'NS-TR-2026-014',
    title: 'Construction of 12m Span RCC Road Overbridge — NH-44 Section',
    department: 'PWD / NHAI',
    location: 'Sagar, Madhya Pradesh',
    value: '₹10.5 Cr',
    deadline: 'Oct 28, 2026',
    category: 'Road & Bridge',
    published: 'Sep 12, 2026',
    status: 'Open',
    description: 'Design and construction of a 12m span RCC bridge including approach roads, earthwork, PCC/mastic paving and crash barriers. Concrete as per IS 456:2000.',
    eligibility: [
      { item: 'Experience: 3 similar bridge/ROB projects in last 7 years', met: true },
      { item: 'Minimum annual turnover ₹25 Cr in last 3 financial years', met: true },
      { item: 'Registration: CPWD / State PWD approved contractor (Class A)', met: true },
      { item: 'Technical staff: certified structural engineer on team', met: true },
      { item: 'Equipment: crawler crane ≥ 25T, concrete pump', met: true },
      { item: 'Performance: no blacklisting / poor performance records', met: true },
    ],
  },
  {
    id: 'NS-TR-2026-011',
    title: 'Rural Water Supply & Treatment Plant (10 MLD)',
    department: 'Jal Nigam',
    location: 'Jabalpur, Madhya Pradesh',
    value: '₹24 Cr',
    deadline: 'Nov 05, 2026',
    category: 'Water Infrastructure',
    published: 'Sep 05, 2026',
    status: 'Open',
    description: 'Construction of 10 MLD water treatment plant with intake well, pump house, settling tanks and 35 km distribution network under Jal Jeevan Mission.',
    eligibility: [
      { item: 'Experience: 2 water infra projects ≥ ₹15 Cr in last 7 years', met: true },
      { item: 'Minimum annual turnover ₹30 Cr in last 3 financial years', met: false },
      { item: 'Registration: valid contractor license in relevant class', met: true },
      { item: 'Technical staff: water-treatment experienced engineers', met: true },
      { item: 'Financial capacity: net worth ≥ ₹12 Cr', met: false },
      { item: 'EMD: ₹60 Lakh via bank guarantee or deposit', met: true },
    ],
  },
  {
    id: 'NS-TR-2026-009',
    title: 'Construction of 4-Lane State Highway (18 km)',
    department: 'State Highway Authority',
    location: 'Indore–Dewas, Madhya Pradesh',
    value: '₹68 Cr',
    deadline: 'Dec 12, 2026',
    category: 'Road & Bridge',
    published: 'Aug 20, 2026',
    status: 'Open',
    description: 'Widening and pavement of 18 km section to 4 lanes including 3 minor bridges, culverts, drainage and road furniture. Performance-based maintenance of 5 years.',
    eligibility: [
      { item: 'Experience: 2 highway projects ≥ ₹50 Cr in last 7 years', met: true },
      { item: 'Minimum annual turnover ₹90 Cr in last 3 financial years', met: false },
      { item: 'Registration: Class AA contractor with state authority', met: true },
      { item: 'Technical staff: qualified highway engineers & surveyor', met: true },
      { item: 'Equipment: asphalt plant, paver, rollers (owned fleet preferred)', met: true },
      { item: 'Performance: valid ISO 9001 certified contractor', met: true },
    ],
  },
  {
    id: 'NS-TR-2026-006',
    title: 'Government School Campus Development (20 Schools)',
    department: 'Education Dept.',
    location: 'Gwalior Division, MP',
    value: '₹6.2 Cr',
    deadline: 'Oct 18, 2026',
    category: 'Buildings',
    published: 'Aug 02, 2026',
    status: 'Open',
    description: 'Development of school infrastructure across 20 sites — classrooms, toilets, boundary walls, water storage and repairs under Samagra Shiksha Abhiyan.',
    eligibility: [
      { item: 'Experience: educational building projects ≥ ₹3 Cr', met: true },
      { item: 'Minimum annual turnover ₹8 Cr in last 3 financial years', met: true },
      { item: 'Registration: Class B contractor license', met: true },
      { item: 'Technical staff: site engineers & safety officer', met: true },
      { item: 'Equipment: mixed fleet with own vehicles', met: true },
      { item: 'Performance: previous govt. projects completed on time', met: true },
    ],
  },
  {
    id: 'NS-TR-2026-003',
    title: 'Smart City Street Lighting & Public Wi-Fi',
    department: 'Smart City Mission',
    location: 'Ujjain, Madhya Pradesh',
    value: '₹9.8 Cr',
    deadline: 'Nov 20, 2026',
    category: 'Electrical / ICT',
    published: 'Jul 15, 2026',
    status: 'Open',
    description: 'GPS-synchronised LED street lighting on 120 km of roads with centralised control system and 40 public Wi-Fi hotspots with 5-year O&M.',
    eligibility: [
      { item: 'Experience: smart lighting / ICT projects ≥ ₹5 Cr', met: true },
      { item: 'Minimum annual turnover ₹12 Cr in last 3 financial years', met: true },
      { item: 'Registration: electrical contractor license; EPE certification', met: true },
      { item: 'Technical staff: electrical + network engineers', met: true },
      { item: 'Equipment: boom lifts, cable laying machinery', met: false },
      { item: 'Performance: no defaults on previous Smart City tenders', met: true },
    ],
  },
]

// ===== DIGITAL AUDIT TRAIL =====
export const auditTrail = [
  { step: 'Tender Published', by: 'NHAI / PWD Portal', when: 'Sep 12, 2026 · 10:04 AM', note: 'e-NIT uploaded with BOQ, drawings & SBD' },
  { step: 'Applications Received', by: 'e-Procurement Gateway', when: 'Sep 12 – Sep 28, 2026', note: '128 contractors selected only once (no duplicates)' },
  { step: 'Eligibility Checked', by: 'System + Eligibility Officer', when: 'Sep 30, 2026', note: 'Auto-verification of turnover, class & experience' },
  { step: 'Documents Verified', by: 'Document Verification Cell', when: 'Oct 02, 2026', note: 'Aadhaar/e-verified, GST, PAN, EPF/ESI compliance' },
  { step: 'Technical Evaluation', by: 'Technical Evaluation Committee', when: 'Oct 05–08, 2026', note: 'Weighted scoring of 6 criteria (40 marks technical)' },
  { step: 'Financial Evaluation', by: 'Finance Wing', when: 'Oct 10, 2026', note: 'L1 determination on audited BOQ rates' },
  { step: 'Committee Recommendation', by: 'Tender Committee', when: 'Oct 12, 2026', note: 'Unanimous recommendation minuted in record' },
  { step: 'Authorized Approval', by: 'Approving Authority', when: 'Oct 15, 2026', note: 'Annexure-A gazette reference recorded' },
  { step: 'Work Order Issued', by: 'Contracts Wing', when: 'Oct 18, 2026', note: 'Digital work order with QR-authenticated copy' },
  { step: 'Project Execution & Monitoring', by: 'Nirman SETU + Site PIU', when: 'Nov 2026 – ongoing', note: 'Daily progress, materials & payment logged live' },
  { step: 'Completion & Handover', by: 'Joint Measurement Team', when: 'Expected Sep 2027', note: 'Geotagged measurements, defect liability period' },
]